;
CLKMODE            = $0080
CONIO              = $0001        
CONSTA             = $0000        
LED7SEG            = $0081

;
mon               = $F000
clk_spd_change    = $F1E2 
dump              = $F164
getln             = $F0C5 
hex2nib           = $F1AD
hexstr_de         = $F1CB 
print_byte        = $F120
print_endl        = $F12D 
print_err_msg     = $F13E
print_nibble      = $F111
print_str_hl      = $F136 

print_hl_dec       = $F212 
div16_8            = $F1E7 
